### ISSUE TITLE
stats.nba.com now checks referal

### ISSUE THREAD

**Issue by wescleveland** [dblackrun/scrape_nba#1]
Hey just a heads up on my fork of this repo I had to modify the headers sent when fetching from stats.nba.com.  Sample code below, note that I've switched to the requests library when fetching the json.

```python
    headers = {'User-agent': 'Mozilla/5.0', 'referer': 'http://stats.nba.com/scores/'}
    print("fetching %s" % url)
    response = requests.get(url, headers=headers)
```

**Comment by dblackrun** [comment]
Thanks for the heads up. I added the referer to the headers.
